config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    post "/like", to: "likes#like_trigger"
    resources :comments, only: [:create, :destroy]
    get '/mypage', to: 'posts#show'
  end
  resources :follows, only: [:create, :destroy]
  
  
  # post "/mypage" => 'posts#mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    has_many :comments
    mount_uploader :image, PostImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower

  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed
  
  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_id, only: [:destroy]
    def create
        new_comment = Comment.new(content: params[:content], post_id: params[:post_id], user_id: current_user.id)
        
        new_comment.save
        redirect_back fallback_location: root_path
    end
    
    def destroy
        #comment = Comment.find_by(id: params[:id])
        @comment.destroy
        redirect_back fallback_location: root_path 
    end
    
    private
        def check_id
            @comment = Comment.find_by(id: params[:id])
            redirect_back fallback_location: root_path if @comment.user.id != current_user.id
        end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    Follow.create(followed_id: params[:followed_id], follower_id: current_user.id)
    redirect_back fallback_location: root_path
  end

  def destroy
    Follow.find_by(followed_id: params[:id], follower_id: current_user.id).destroy
    redirect_back fallback_location: root_path
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def like_trigger
        like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
        
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:post_id])
        else
            like.destroy
        end
        
        redirect_back fallback_location: root_path
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_id, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end
  
  def new
  end
  
  def create
    new_post = Post.new(user_id: current_user.id, content: params[:content], image: params[:image])
    if new_post.save
      redirect_to root_path
    else
      redirect_to new_post_path
    end
  end
  
  def edit
    #@post = Post.find_by(id: params[:id])
  end
  
  def update
    #@post = Post.find_by(id: params[:id])
    #redirect_to root_path if @post.user_id != current_user.id
    
    @post.content = params[:content]
    
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def destroy 
    #@post = Post.find_by(id: params[:id])
    #redirect_to root_path if @post.user_id != current_user.id
    
    @post.destroy
    redirect_to root_path
  end
  
  def show
    @myposts = Post.where(user_id: [current_user.id, Follow.find_by(followed_id: params[:followed_id], follower_id: current_user.id)])
    @posts_count = current_user.posts.length
  end
  
  private
    def check_id
      @post = Post.find_by(id: params[:id])
      redirect_to root_path if @post.user_id != current_user.id
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper teal #ff8f00 amber darken-3">
        <a href="/" class="brand-logo center",>Blog</a></span>
        <ul class="right hide-on-med-and-down">
          
          <% if user_signed_in? %>
            <li><%=link_to current_user.name, post_mypage_path(current_user.id), method: 'get' %></li>
            <li><%=link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
          <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Sign in</a></li>
          <% end %>
          <li class="active"><a href="/posts">Posts</a></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card">
    <div class="card post" data-post-id="<%= post.id %>">
        <div class="card-content">
            <span class="card-title"><%= post.user.name %></span>
            <span><%= post.created_at %></span>
                <% if user_signed_in? && current_user != post.user %>
                  <% if current_user.followings.include?(post.user) %>
                    <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                      <button class="btn margin-bottom deep-orange lighten-3">UnFollow</button>
                    <% end %>
                  <% else %>
                    <%= form_tag follows_path, method: :post, class: "right" do %>
                      <input type="hidden" name="followed_id" value="<%= post.user.id %>" />
                      <button class="btn margin-bottom deep-orange lighten-3">Follow</button>
                    <% end %>
                  <% end %>
                <% end %>
            <div class="card-image">
                <% if post.image.url %>
                  <img class="margin-bottom" src="<%= post.image.url %>" />
                <% end %>
            </div>
            <p class= "pre-line"><%= post.content %></p>
        </div>
    </div>
    
    <div class="card-action">
        <img src="/thumbs-up.png"></img><span class="orange-text text-darken-4"><%= post.likes.size %></span>
        <% if current_user.is_like?(post)%>
            <%= link_to "Cancel", post_like_path(post), method: "post"%>
        <% else %>
            <%= link_to "Like", post_like_path(post), method: "post" %>
        <% end %>
        <% if current_user.id == post.user_id %>
            <%= link_to "Delete", post_path(post), method: "delete", class: "right" %>
            <%= link_to "Edit", edit_post_path(post), class: "right" %>
        <% end %>    
        
        <%= form_tag post_comments_path(post) do %>
            <div  class="input-field">
                <%= text_area_tag :content, nil, class: "materialize-textarea" %>
            </div>
            <div class="input-field">
                <%= button_tag "Submit", class: "btn orange lighten-3" %>
            </div>
        <% end %>
        <% if post.comments.present? %>
            <ul class="collection">
                <% post.comments.each do |comment| %>
                    <li class="collection-item">
                        <span class="title"><%= comment.user.name %></span>
                        <span class="right"><%= comment.created_at %></span>
                        <p class="pre-line"><%= comment.content %></p>
                        <% if comment.user.id == current_user.id %>
                            <div><%= link_to "Delete", post_comment_path(post, comment), method: "delete" %></div>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class= "container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
              <span class="card-title">수정 하기</span>
              <%= form_tag post_path(@post), method: "patch" do %>
                  <input type="hidden" name="id" value="<%=@post.id%>">
                  <div class= "input-field">
                      <%= text_area_tag :content, @post.content, class: "materialize-textarea"%>
                  </div>
                  
                  <div class="input-field">
                      <%= button_tag "수정하기", class: "btn"%>
                  </div>
              <% end %>
            </div>
          
        </div>
      </div>
 </div>

app/views/posts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m3">
            <div class="card">
                <div class="card-image">
                    <img src= "/human.jpeg"></img>
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>작성하신 글은 <%= @posts_count %> 개 입니다.</p>
                    <p>Follower : <%= current_user.followers.length %></p>
                    <p>Following : <%= current_user.followings.length %></p>
                    <p><a class="waves-effect waves-light btn orange lighten-3" href="/users/edit">Edit User</a></p>
                    
                    <!--<%= link_to new_post_path do %>-->
                    <!--    <button class="btn">글 쓰 기</button>-->
                    <!--<% end %>-->
                </div>
            </div>
        </div>
        <span class="fixed-action-btn">
                <%= link_to new_post_path do %>
                    <button class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></button>
                <% end %>
        </span>
        <div class="col s12 m8">
            <% @posts.each do |post| %>
               <%= render partial: "post", object: post %>
            <% end %>
        </div>
    </div>
</div>

app/views/posts/new.html.erb
<div class= "container">
    <div class="row">
        <div class="card col s12">
            <div class="card-content">
              <span class="card-title">새 글 작성하기</span>
              <%= form_tag posts_path, multipart: true do %>
                  <div class="input-field">
                    <%= file_field_tag :image %>
                  </div>
                  
                  <div class= "input-field">
                      <%= text_area_tag :content, nil, class: "materialize-textarea"%>
                  </div>
                  
                  <div class="input-field">
                      <%= button_tag "작성하기", class: "btn orange lighten-3"%>
                  </div>
              <% end %>
            </div>
          
        </div>
      </div>
 </div>

app/views/posts/show.html.erb
<div class="container">
    <div class="row">
        <div class="col s12 m3">
            <div class="card">
                <div class="card-image">
                    <img src= "/human.jpeg"></img>
                </div>
                <div class="card-content">
                    <div class="card-title"><%= current_user.name %></div>
                    <p>이메일 : <%= current_user.email %></p>
                    <p>작성하신 글은 <%= @posts_count %> 개 입니다.</p>
                    <p>Follower : <%= current_user.followers.length %></p>
                    <p>Following : <%= current_user.followings.length %></p>
                    <p><a class="waves-effect waves-light btn orange lighten-3" href="/users/edit">Edit User</a></p>
                    <!--<%= link_to new_post_path do %>-->
                    <!--    <button class="btn">글 쓰 기</button>-->
                    <!--<% end %>-->
                </div>
            </div>
        </div>
        <span class="fixed-action-btn">
                <%= link_to new_post_path do %>
                    <button class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></button>
                <% end %>
        </span>
        <div class="col s12 m8">
            <% @myposts.each do |post| %>
                <div class="card">
                    <div class="card post" data-post-id="<%= post.id %>">
                        <div class="card-content">
                            <span class="card-title"><%= post.user.name %></span>
                            <span><%= post.created_at %></span>
                                <% if user_signed_in? && current_user != post.user %>
                                  <% if current_user.followings.include?(post.user) %>
                                    <%= form_tag follow_path(post.user.id), method: :delete, class: "right" do %>
                                      <button class="btn margin-bottom deep-orange lighten-3">UnFollow</button>
                                    <% end %>
                                  <% else %>
                                    <%= form_tag follows_path, method: :post, class: "right" do %>
                                      <input type="hidden" name="followed_id" value="<%= post.user.id %>" />
                                      <button class="btn margin-bottom deep-orange lighten-3">Follow</button>
                                    <% end %>
                                  <% end %>
                                <% end %>
                            <div class="card-image">
                                <% if post.image.url %>
                                  <img class="margin-bottom" src="<%= post.image.url %>" />
                                <% end %>
                            </div>
                            <p class= "pre-line margin-top"><%= post.content %></p>
                        </div>
                    </div>
                    
                    <div class="card-action">
                        <img src="/thumbs-up.png"></img><span class="orange-text text-darken-4"><%= post.likes.size %></span>
                            <% if current_user.is_like?(post)%>
                                <%= link_to "Cancel", post_like_path(post), method: "post"%>
                            <% else %>
                                <%= link_to "Like", post_like_path(post), method: "post" %>
                            <% end %>
                            <% if current_user.id == post.user_id %>
                                <%= link_to "Delete", post_path(post), method: "delete", class: "right" %>
                                <%= link_to "Edit", edit_post_path(post), class: "right" %>
                            <% end %>   
                        <%= form_tag post_comments_path(post) do %>
                            <div  class="input-field">
                                <%= text_area_tag :content, nil, class: "materialize-textarea" %>
                            </div>
                            <div class="input-field">
                                <%= button_tag "Submit", class: "btn orange lighten-3" %>
                            </div>
                        <% end %>
                        <% if post.comments.present? %>
                            <ul class="collection">
                                <% post.comments.each do |comment| %>
                                    <li class="collection-item">
                                        <span class="title"><%= comment.user.name %></span>
                                        <span class="right"><%= comment.created_at %></span>
                                        <p class="pre-line"><%= comment.content %></p>
                                        <% if comment.user.id == current_user.id %>
                                            <div><%= link_to "Delete", post_comment_path(post, comment), method: "delete" %></div>
                                        <% end %>
                                    </li>
                                <% end %>
                            </ul>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>